/**
 * InventoryAPI
 * Orkiv Inventory API client 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['InventoryClient/ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.InventoryClient) {
      root.InventoryClient = {};
    }
    root.InventoryClient.Order = factory(root.InventoryClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Order model module.
   * @module InventoryClient/InventoryClient.model/Order
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Order</code>.
   * @alias module:InventoryClient/InventoryClient.model/Order
   * @class
   */
  var exports = function() {
    var _this = this;





















  };

  /**
   * Constructs a <code>Order</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:InventoryClient/InventoryClient.model/Order} obj Optional instance to populate.
   * @return {module:InventoryClient/InventoryClient.model/Order} The populated <code>Order</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('order_id')) {
        obj['order_id'] = ApiClient.convertToType(data['order_id'], 'String');
      }
      if (data.hasOwnProperty('info_email')) {
        obj['info_email'] = ApiClient.convertToType(data['info_email'], 'String');
      }
      if (data.hasOwnProperty('info_first')) {
        obj['info_first'] = ApiClient.convertToType(data['info_first'], 'String');
      }
      if (data.hasOwnProperty('info_last')) {
        obj['info_last'] = ApiClient.convertToType(data['info_last'], 'String');
      }
      if (data.hasOwnProperty('phone')) {
        obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
      }
      if (data.hasOwnProperty('shipset')) {
        obj['shipset'] = ApiClient.convertToType(data['shipset'], 'Boolean');
      }
      if (data.hasOwnProperty('info_adr1')) {
        obj['info_adr1'] = ApiClient.convertToType(data['info_adr1'], 'String');
      }
      if (data.hasOwnProperty('info_adr2')) {
        obj['info_adr2'] = ApiClient.convertToType(data['info_adr2'], 'String');
      }
      if (data.hasOwnProperty('info_cty')) {
        obj['info_cty'] = ApiClient.convertToType(data['info_cty'], 'String');
      }
      if (data.hasOwnProperty('info_zip')) {
        obj['info_zip'] = ApiClient.convertToType(data['info_zip'], 'String');
      }
      if (data.hasOwnProperty('state')) {
        obj['state'] = ApiClient.convertToType(data['state'], 'String');
      }
      if (data.hasOwnProperty('info_sadr1')) {
        obj['info_sadr1'] = ApiClient.convertToType(data['info_sadr1'], 'String');
      }
      if (data.hasOwnProperty('info_sadr2')) {
        obj['info_sadr2'] = ApiClient.convertToType(data['info_sadr2'], 'String');
      }
      if (data.hasOwnProperty('info_scty')) {
        obj['info_scty'] = ApiClient.convertToType(data['info_scty'], 'String');
      }
      if (data.hasOwnProperty('info_szip')) {
        obj['info_szip'] = ApiClient.convertToType(data['info_szip'], 'String');
      }
      if (data.hasOwnProperty('sstate')) {
        obj['sstate'] = ApiClient.convertToType(data['sstate'], 'String');
      }
      if (data.hasOwnProperty('tax_amount')) {
        obj['tax_amount'] = ApiClient.convertToType(data['tax_amount'], 'Number');
      }
      if (data.hasOwnProperty('shipping_amount')) {
        obj['shipping_amount'] = ApiClient.convertToType(data['shipping_amount'], 'Number');
      }
      if (data.hasOwnProperty('amount_total')) {
        obj['amount_total'] = ApiClient.convertToType(data['amount_total'], 'Number');
      }
      if (data.hasOwnProperty('itemIDs')) {
        obj['itemIDs'] = ApiClient.convertToType(data['itemIDs'], ['String']);
      }
    }
    return obj;
  }

  /**
   * Order ID
   * @member {String} order_id
   */
  exports.prototype['order_id'] = undefined;
  /**
   * Customer email
   * @member {String} info_email
   */
  exports.prototype['info_email'] = undefined;
  /**
   * Customer first name
   * @member {String} info_first
   */
  exports.prototype['info_first'] = undefined;
  /**
   * Customer last name
   * @member {String} info_last
   */
  exports.prototype['info_last'] = undefined;
  /**
   * Customer phone number
   * @member {String} phone
   */
  exports.prototype['phone'] = undefined;
  /**
   * Customer billing address matches shipping address
   * @member {Boolean} shipset
   */
  exports.prototype['shipset'] = undefined;
  /**
   * Customer billing address line '1'
   * @member {String} info_adr1
   */
  exports.prototype['info_adr1'] = undefined;
  /**
   * Customer billing address line '2'
   * @member {String} info_adr2
   */
  exports.prototype['info_adr2'] = undefined;
  /**
   * Customer billing city
   * @member {String} info_cty
   */
  exports.prototype['info_cty'] = undefined;
  /**
   * Customer billing zip code
   * @member {String} info_zip
   */
  exports.prototype['info_zip'] = undefined;
  /**
   * Customer billing state
   * @member {String} state
   */
  exports.prototype['state'] = undefined;
  /**
   * Customer shipping address line '1'
   * @member {String} info_sadr1
   */
  exports.prototype['info_sadr1'] = undefined;
  /**
   * Customer shipping address line '2'
   * @member {String} info_sadr2
   */
  exports.prototype['info_sadr2'] = undefined;
  /**
   * Customer shipping city
   * @member {String} info_scty
   */
  exports.prototype['info_scty'] = undefined;
  /**
   * Customer shipping zip code
   * @member {String} info_szip
   */
  exports.prototype['info_szip'] = undefined;
  /**
   * Customer shipping state
   * @member {String} sstate
   */
  exports.prototype['sstate'] = undefined;
  /**
   * Tax amount in hundreds. Must divide by '100' for USD value
   * @member {Number} tax_amount
   */
  exports.prototype['tax_amount'] = undefined;
  /**
   * Shipping total in USD
   * @member {Number} shipping_amount
   */
  exports.prototype['shipping_amount'] = undefined;
  /**
   * Checkout total in USD
   * @member {Number} amount_total
   */
  exports.prototype['amount_total'] = undefined;
  /**
   * Array of items purchased at checkout
   * @member {Array.<String>} itemIDs
   */
  exports.prototype['itemIDs'] = undefined;



  return exports;
}));


