/**
 * InventoryAPI
 * Orkiv Inventory API client 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['InventoryClient/ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.InventoryClient) {
      root.InventoryClient = {};
    }
    root.InventoryClient.Variation = factory(root.InventoryClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Variation model module.
   * @module InventoryClient/InventoryClient.model/Variation
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Variation</code>.
   * @alias module:InventoryClient/InventoryClient.model/Variation
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>Variation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:InventoryClient/InventoryClient.model/Variation} obj Optional instance to populate.
   * @return {module:InventoryClient/InventoryClient.model/Variation} The populated <code>Variation</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('priceChange')) {
        obj['priceChange'] = ApiClient.convertToType(data['priceChange'], 'Number');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
    }
    return obj;
  }

  /**
   * Variation name
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * New price to set if variation is set (in hundreds)
   * @member {Number} priceChange
   */
  exports.prototype['priceChange'] = undefined;
  /**
   * System ID of variation
   * @member {String} id
   */
  exports.prototype['id'] = undefined;



  return exports;
}));


